<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fw_mettigels"
 *
 * Auto generated by Extension Builder 2018-03-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Mettigels_Template',
    'description' => 'Template für die Mettigels',
    'category' => 'templates',
    'author' => 'Andreas Fineske',
    'author_email' => 'afineske@finiweb.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
